// src/app/components/header/header.component.ts
import { Component, OnInit } from '@angular/core';

import { HeaderService } from '../../service/header.service';

import { Router } from '@angular/router';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {

  tokens = {
    token:JSON.parse( localStorage.getItem('token')).token,
  }
  headtoken;

  constructor(private token1:HeaderService,private router:Router) { }

  ngOnInit(): void {

     this.token1.Header(this.tokens).subscribe(data=>{
      this.headtoken=data
      console.log(this.headtoken)
      if(this.headtoken === undefined){
        this.router.navigate(['/login'])
      }
   
    });
  }
  onLogout = () => {
    localStorage.removeItem('token');
    this.router.navigate(['/login'])
  }

}


 <div class="full">
       <div><img class="img-responsive" width="150px" alt="Railyatri.in" src="https://images.railyatri.in/ry-logo.png"></div>
      <div class="head"> </div>
      <div class="user">{{this.headtoken.user.name}}
            <div *ngIf="this.headtoken.user.name=='Indhu'">
                  <a href="/change" >SuperAdmin</a>
            </div>
            <div>
                  <a href="/change" *ngIf="this.headtoken.user.isadmin==1">Admin</a>   
                  <a  *ngIf="this.headtoken.user.isadmin==0">User</a>   
            </div>
       <div class="logbtn"> <a  class="whitelink" (click)="onLogout()" > Logout </a> </div> </div>
</div>

// src/components/Header/Header.jsx
import React, { Component } from 'react'
import '../Header/Header.css'
import {Redirect, withRouter} from 'react-router-dom'
import logo from "../../Assets/IRCTC.png"
class Header extends Component {
    constructor(props) {
        super(props)

        this.state = {
            showMo:false,
            authdata: {
                'user': {
                    'name': ''
                }
            }
        }
    }
    componentDidMount = async() => {
        if (localStorage.getItem('token')) {
            await fetch('http://localhost:3050/head', {
                method: 'post',
                body: JSON.stringify({
                    token: JSON
                        .parse(localStorage.getItem('token'))
                        .token
                }),
                    headers: {
                        'Content-Type': 'application/json'
                    }
                })
                .then(res => res.json())
                .then(data => this.setState({authdata: data}))
                .catch(() => {
                    console.log('error')
                    this
                        .props
                        .history
                        .push("/login")
                })
        }
    }

    handlelogout = (e) => {
        localStorage.removeItem('token');
        window.location.reload();

    }
    handleMenu = (e) => {
        this.setState({
            showMo:!this.state.shoMo
        })
    }
    render() {
        return (
            (!localStorage.getItem('token')) ? <Redirect to="/login"/>
            : <div>
                <div className="full">
                    <div className="head">
                     <div><img  src={logo} alt="logo" width="110px" height="70px"/></div>
                    </div>
                    <p className={`menu${this.state.showMo === false ? '': '1'}`} onClick={this.handleMenu}>
                            <div></div>
                            <div></div>
                            <div></div>
                    </p>
  
                  {
                  this.state.showMo?  <div className="user">{this.state.authdata.user.name}
                        <div className="logbtn">
                            <p className="whitelink" onClick={e => this.handlelogout(e)}>
                                Logout
                            </p>
                        </div>
                        <a  id="book" href="/myBookings" date={this.state.date}>MyBookings</a>
                    </div>
                    :<div></div>}

                </div>
                    
            </div>
            )
    }
}

export default withRouter(Header)
